[package]
name = "tpmt"
description = "Modding toolkit for The Legend of Zelda: Twilight Princess."
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
tpmt-pipeline.workspace = true

thiserror.workspace = true
clap.workspace = true

[lints]
workspace = true
