[package]
name = "tpmt-disc"
description = "Reading and writing GameCube disc images."
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
tpmt-bytes.workspace = true
thiserror.workspace = true
sha1.workspace = true # disc identity

[lints]
workspace = true
