[package]
name = "tpmt-disc"
description = "Reading and writing GameCube disc images."
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
tpmt-bytes.workspace = true
thiserror.workspace = true
encoding_rs.workspace = true # file table names
sha1.workspace = true # disc identity

[lints]
workspace = true
