[package]
name = "tpmt-bmg"
description = "BMG binary message files."
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
tpmt-bytes.workspace = true
thiserror.workspace = true
encoding_rs.workspace = true # message text
serde.workspace = true
serde_json.workspace = true # editable

[lints]
workspace = true
